config/routes.rb
Rails.application.routes.draw do
  resources :dwarf_skills
  devise_for :users, controllers: {registrations: "users/registrations"}
  root to: 'pages#home'
  resources :dwarves do
    resources :rents, only: [:new, :create]
  end
  resources :rents, only: [:destroy, :update, :show] do
    resources :reviews, only: [:new, :create, :index, :show]
  end
  resources :dwarves do
    resources :dwarf_skills
  end

  resources :rents, only: [:index, :show, :edit, :update]

end

app/controllers/dwarves_controller.rb
class DwarvesController < ApplicationController
skip_before_action :authenticate_user!
  def index
    search = params[:search]

    if search.present?
      if search[:skill].empty? && !search[:location].empty?
        @dwarves = Dwarf.global_search(search[:location])
        create_markers(@dwarves)
      elsif !search[:skill].empty? && search[:location].empty?
        @dwarves = Dwarf.global_search(search[:skill])
        create_markers(@dwarves)
      elsif !search[:skill].empty? && !search[:location].empty?
        dwarf_skill = Dwarf.global_search(search[:skill])
        dwarf_location = Dwarf.global_search(search[:location])
        @dwarves = (dwarf_skill & dwarf_location)
        create_markers(@dwarves)
      elsif search[:skill].empty? && search[:location].empty?
        @dwarves = Dwarf.all
        create_markers(@dwarves)
      end
    else
      @dwarves = Dwarf.all
      create_markers(@dwarves)
    end

  end

  def new
    @dwarf = Dwarf.new
  end

  def show
    @dwarf = Dwarf.find(params[:id])
  end

  def create
    @dwarf = Dwarf.new(dwarf_params)
    @dwarf.user_id = current_user.id
    @dwarf.save

    redirect_to dwarves_path
  end

  def edit
    @dwarf = Dwarf.find(params[:id])
  end

  def update
    @dwarf = Dwarf.find(params[:id])
    @dwarf.update(dwarf_params)

    redirect_to dwarves_path
  end

  def destroy
    @dwarf = Dwarf.find(params[:id])
    @dwarf.destroy

    redirect_to dwarves_path
  end

  private

  def create_markers(dwarves)
    if dwarves.class == Array && dwarves != []
      @markers = dwarves.map do |dwarf|
        {
          lat: dwarf.latitude,
          lng: dwarf.longitude,
          info_window: render_to_string(partial: "info_window", locals: { dwarf: dwarf }),
          image_url: helpers.asset_url('dwarf-logo.png')
        }
      end
    elsif  dwarves != []
      @markers = dwarves.geocoded.map do |dwarf|
        {
          lat: dwarf.latitude,
          lng: dwarf.longitude,
          info_window: render_to_string(partial: "info_window", locals: { dwarf: dwarf }),
          image_url: helpers.asset_url('dwarf-logo.png')
        }
      end
    end
  end

  def dwarf_params
    params.require(:dwarf).permit(:nickname, :size, :gender, :description, :price_per_hour, :location, photos: [])
  end
end

app/views/dwarves/_info_window.html.erb
<%= link_to dwarf.nickname, dwarf_path(dwarf.id) %>
<p><%= dwarf.location %></p>
<%= cl_image_tag dwarf.photos.first.key, :width=>100, :height=>100, :gravity=>"faces", :crop=>"thumb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

app/views/dwarves/edit.html.erb
<div class="form-container">
  <h2>Mettre à jour mon profil</h2>
  <%= simple_form_for(@dwarf) do |f| %>
    <div class="form-inputs">
      <%= f.input :nickname,
                  required: true,
                  input_html: { autocomplete: "nickname" } %>
      <%= f.input :size,
                  required: true,
                  input_html: { autocomplete: "size" } %>
      <%= f.input :gender,
                  required: true,
                  input_html: { autocomplete: "gender" }%>
      <%= f.input :description,
                  required: true,
                  input_html: { autocomplete: "description" } %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.input :price_per_hour,
                  required: true,
                  input_html: { autocomplete: "price per hour" } %>
      <%= f.input :location,
                  required: true,
                  input_html: { autocomplete: "location" } %>
    </div>
    <div class="show-skills-container">
      <p>Mes usages</p>
        <%  @dwarf.dwarf_skills.each do |skill| %>
          <div class="skill">
            <%=  Skill.find(skill.skill_id).skill %>
          </div>
        <% end %>
    </div>
  <%= link_to "Add a skill", new_dwarf_dwarf_skill_path(@dwarf), class: "btn btn-primary" %>

    <div class="form-actions">
    <hr>
      <%= f.button :submit, "Edit", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/dwarves/index.html.erb
<div class="dwarves-index-search-bar">
  <%= render 'shared/search_bar' %>
    <h1>Des nains pour tous les gouts! Et avec tous les gouts!</h1>
  <div class="cards-dwarf-container">
    <div class="cards-dwarf">
        <% if @dwarves.join == "" %>
       <div class="no-result">
        <h2>Aucun nain trouvé avec ces critères <i class="far fa-sad-cry"></i></h2>
       </div>
        <% else %>
        <% @dwarves.each do |dwarf| %>
          <%= render 'shared/card', dwarf: dwarf%>
        <% end %>
        <% end %>
    </div>
    <div id="map"
      style="width: 100%; height: 700px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/dwarves/new.html.erb
<div class="form-container">
  <h2>Create my dwarf profile</h2>
  <%= simple_form_for(@dwarf) do |f| %>
    <div class="form-inputs">
      <%= f.input :nickname,
                  required: true,
                  input_html: { autocomplete: "nickname" } %>
      <%= f.input :size,
                  collection: 80..150, prompt: "Select your size in cm"%>
      <%= f.input :gender,
                  required: true, collection: [:Male, :Female, :Shemale, :Neutrale],
                  input_html: { autocomplete: "gender" }%>
      <%= f.input :description,
                  required: true,
                  input_html: { autocomplete: "description" } %>
      <%= f.input :photos, as: :file,
                  required: true,
                  input_html: { multiple: true } %>
      <%= f.input :price_per_hour,
                  required: true,
                  input_html: { autocomplete: "price per hour" } %>
      <%= f.input :location,
                  required: true,
                  input_html: { autocomplete: "location" } %>

    </div>
    <hr>
    <div class="form-actions">
      <%= f.button :submit, "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/dwarves/show.html.erb
<div class="show-container">
    <h1 class="text-center"><%= @dwarf.nickname %></h1>
  <div class="show-content">
    <div class="show-img">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% i = 1 %>
      <% n = @dwarf.photos.count - 1 %>
      <%= cl_image_tag @dwarf.photos[0].key, class:"d-block" %>
    </div>
    <% n.times do %>
     <div class="carousel-item">
       <%= cl_image_tag @dwarf.photos[i].key, class:"d-block" %>
       <% i += 1 %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    </div>
    <div class="show-infos">
      <h2 class="text-center">Ma taille</h2>
      <h4 class="text-center"><%= @dwarf.size %> cm</h4>
      <br>
      <h2 class="text-center">Ma devise</h2>
      <h4 class="text-center">"<%= @dwarf.description.capitalize %>"</h4>
      <hr>
      <div class="show-skills-container">
        <%  @dwarf.dwarf_skills.each do |skill| %>
        <div class="skill">
          <%=  Skill.find(skill.skill_id).skill %>
        </div>
        <% end %>
      </div>
        <i class="far fa-comment"></i>
        <% rents = Rent.where(dwarf_id: @dwarf.id) %>
          <% rents.each do |rent| %>
        <div class="reviews_container">
              <div class="show-comment">
                <h4>"<%= rent.review %>"</h4>
              </div>
              <% stars = rent.rating.to_i  %>
              <% stars.times do %>
              <div class="show-stars">
                <i class="fas fa-star"></i>
              </div>
            <% end %>
        </div>
          <% end %>
        <br>

        <div class="text-center">
          <%= link_to 'Loue-moi!', new_dwarf_rent_path(@dwarf.id), class: "btn btn-primary", id: "show-hire-btn"  %>
        </div>

    </div>
  </div>
 <%= link_to 'Retour à la collection de nain', dwarves_path, class: "btn btn-warning", id: "show-back-btn"  %>
</div>