config/routes.rb
Rails.application.routes.draw do
  resources :dwarf_skills
  devise_for :users, controllers: {registrations: "users/registrations"}
  root to: 'pages#home'
  resources :dwarves do
    resources :rents, only: [:new, :create]
  end
  resources :rents, only: [:destroy, :update, :show] do
    resources :reviews, only: [:new, :create, :index, :show]
  end
  resources :dwarves do
    resources :dwarf_skills
  end

  resources :rents, only: [:index, :show, :edit, :update]

end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :dwarf
  belongs_to :user
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @rents = Rent.all
  end

  def new
    @rent = Rent.new
    @dwarf = Dwarf.find(params[:dwarf_id])
  end

  def create
    @dwarf = Dwarf.find(params[:dwarf_id])
    @rent = Rent.new(rent_params)
    @rent[:dwarf_id] = @dwarf.id
    @rent[:user_id] = current_user.id
    if @rent.save
      redirect_to rents_path(current_user.id)
    else render:new
    end
  end

  def edit
    @rent = Rent.find(params[:id])
  end

  def update
    @rent = Rent.find(params[:id])
    @rent.update(rent_params)

    redirect_to rents_path(current_user)
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy

    # no need for app/views/rents/destroy.html.erb
    redirect_to rents_path(current_user)
  end

  private

  def rent_params
    params.require(:rent).permit(:start_date, :end_date, :dwarf_id, :review, :rating)
  end
end

app/views/rents/edit.html.erb
<div class="form-container">
<h1>Commenter cette prestation</h1>
<%= simple_form_for [@rent] do |f| %>
  <%= f.input :review,
    input_html: { autocomplete: "commentaire" } %>
  <%= f.input :rating,
    collection: 0..5,
    prompt: "Note de 0 à 5",
    input_html: { autocomplete: "note" } %>
  <%= f.submit 'Add a review', class: "btn btn-primary" %>
<% end %>
</div>

app/views/rents/index.html.erb
<div class="form-container">
  <h1>MES LOCATIONS</h1>
  <div class="rents-container">
    <hr>
    <% @rents.each do |rent| %>
    <div class="rent-container">
    <div class="rent-text">
      <h2>Nain : <%= rent.dwarf.nickname %> </h2>
        <h2>Du <%= rent.end_date %> </h2>
      <h2>Jusqu'au <%= rent.start_date %> </h2>
      </div>
      <div class="rent-avatar">
      <%  dwarf = Dwarf.find(rent[:dwarf_id]) %>
      <%= cl_image_tag dwarf.photos.first.key, :width=>100, :height=>100, :gravity=>"faces", :crop=>"thumb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </div>
      <div class="rent-button">
      <% if rent.review == nil %>
      <%= link_to "Ajouter une note", edit_rent_path(rent.id), class: "btn btn-warning" %>
      <%= link_to "Annuler",
                  rent_path(rent),
                  method: :delete,
                  class: "btn btn-danger",
                  data: { confirm: "Are you sure?" } %>
      <% end %>
      </div>
    </div>
    <hr>
    <% end %>
  </div>
</div>

app/views/rents/new.html.erb
<div class="form-container">
  <div class="rent">
    <div class="rent-form">
      <% dwarf = Dwarf.find(params[:dwarf_id]) %>
      <h1 id="price" data-price-per-hour="<%=dwarf.price_per_hour%>">Louer <%= dwarf.nickname %></h1>
      <hr>
      <%= simple_form_for [@dwarf, @rent] do |f| %>
        <h2>Date de début</h2>
        <%= f.datetime_field :start_date, as: :date%>
        <h2>Date de fin</h2>
        <%= f.datetime_field :end_date, as: :date%>
        <hr>
        <% if current_user %>
          <%= f.submit 'Réserve ce nain', class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Créer ton compte", new_user_session_path, class: "btn btn-primary" %>
        <% end %>
        <hr>
        <%= link_to 'Retour à nôtre collection de petits hommes', dwarves_path, class: "btn btn-warning"  %>
      <% end %>
      <br>
    <div id="rent-price"><h1 class='text-center'><span id="prout">0</span><span>$</span> </h1></div>
    </div>
    <div class="rent-card">
    <%= render 'shared/card', dwarf: dwarf%>
    </div>
  </div>
</div>