config/routes.rb
Rails.application.routes.draw do
  resources :dwarf_skills
  devise_for :users, controllers: {registrations: "users/registrations"}
  root to: 'pages#home'
  resources :dwarves do
    resources :rents, only: [:new, :create]
  end
  resources :rents, only: [:destroy, :update, :show] do
    resources :reviews, only: [:new, :create, :index, :show]
  end
  resources :dwarves do
    resources :dwarf_skills
  end

  resources :rents, only: [:index, :show, :edit, :update]

end

app/views/shared/_card.html.erb
<div class="card-trip">
   <%= cl_image_tag dwarf.photos[0].key%>
  <div class="card-trip-infos">
    <div>
      <h2><%=link_to dwarf.nickname, dwarf_path(dwarf) %></h2>
      <p><%= dwarf.description %></p>
    </div>
    <h2 class="card-trip-pricing"><%= dwarf.price_per_hour %> $/h</h2>
  </div>
    <div class="skills-container">
      <%  dwarf.dwarf_skills.each do |skill| %>
      <div class="skill">
        <%=  Skill.find(skill.skill_id).skill %>
      </div>
      <% end %>
    </div>
    <div class="reviews_container">
      <% rents = Rent.where(dwarf_id: dwarf.id) %>
      <% rents.each do |rent| %>
      <% if  rent.review != nil %>
        <% stars = rent.rating %>
        <div class="cards-stars">
          <% stars.times do %>
            <i class="fas fa-star"></i>
          <% end %>
      <% end %>
        </div>
        <% end %>
    <div class="hire-btn">
      <%= link_to 'Loue-moi!', new_dwarf_rent_path(dwarf.id), class: "btn btn-primary"  %>
    </div>
    </div>
</div>

app/views/shared/_carousel.html.erb
<section>
  <div class="titre-1">
    <h1>Notre Top 7</h1>
  </div>
    <div class="container-carousel">
        <div class="carousel">
            <input type="radio" name="slides" checked="checked" id="slide-1">
            <input type="radio" name="slides" id="slide-2">
            <input type="radio" name="slides" id="slide-3">
            <input type="radio" name="slides" id="slide-4">
            <input type="radio" name="slides" id="slide-5">
            <input type="radio" name="slides" id="slide-6">
            <input type="radio" name="slides" id="slide-7">
            <ul class="carousel__slides">
            <% dwarves = Dwarf.all  %>
            <% dwarves.each do |dwarf| %>
                <li class="carousel__slide">
                    <figure>
                        <div>
                          <%= cl_image_tag dwarf.photos[0].key, class: "bigimg"%>
                        </div>
                        <figcaption>
                        <div>
                          <%= link_to dwarf.nickname, dwarf_path(dwarf.id) %>
                          <hr>
                          <%= dwarf.description %>
                            <hr>
                          <div class="reviews_container">
                            <% rents = Rent.where(dwarf_id: dwarf.id) %>
                              <% rents.each do |rent| %>
                            <% if  rent.review != nil %>
                                <% stars = rent.rating.to_i  %>
                                  <% stars.times do %>
                                    <i class="fas fa-star"></i>
                            <% end %>
                                <% end %>
                              <% end %>
                          </div>
                          <% if current_user && dwarf.user_id != current_user.id  %>
                          <hr>
                            <div class="hire-btn">
                              <%= link_to 'Loue-moi!', new_dwarf_rent_path(dwarf.id), class: "btn btn-primary"  %>
                            </div>
                          <% end  %>
                        </div>
                        </figcaption>
                    </figure>
                </li>
            <% end %>

            </ul>
            <ul class="carousel__thumbnails">
                <li>
                    <label for="slide-1"><div class="top-carousel">n°1</div></label>
                </li>
                <li>
                    <label for="slide-2"><div class="top-carousel">n°2</div></label>
                </li>
                <li>
                    <label for="slide-3"><div class="top-carousel">n°3</div></label>
                </li>
                <li>
                    <label for="slide-4"><div class="top-carousel">n°4</div></label>
                </li>
                <li>
                    <label for="slide-5"><div class="top-carousel">n°5</div></label>
                </li>
                <li>
                    <label for="slide-6"><div class="top-carousel">n°6</div></label>
                </li>
                <li>
                    <label for="slide-7"><div class="top-carousel">n°7</div></label>
                </li>
            </ul>
        </div>
    </div>
</section>

app/views/shared/_carouselactivity.html.erb
<section>
<div class="titre-1">
<h1>A quoi servira ton nain?</h1>
</div>
<div class="slideshow-container">

  <div class="mySlides fade">
    <div class="numbertext">1 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453010/y0l7vdv3r7jfay6zggmg.jpg" class="activityimg" style="width:100%">
    <div class="text">Fiesta naine!</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">2 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453030/ralisgx3fppepo0upyjs.jpg" class="activityimg" style="width:100%">
    <div class="text">Lancé de nain!</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">3 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453059/pupydlpnnty4qqdlvyjc.jpg" class="activityimg" style="width:100%">
    <div class="text">Animation enterrements!</div>
  </div>

  <div class="mySlides fade">
    <div class="numbertext">4 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629465640/w40eyhufdr5eupntmqee.jpg" class="activityimg"" style="width:100%">
    <div class="text">Football!</div>
  </div>  

  <div class="mySlides fade">
    <div class="numbertext">5 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453115/acv1avydwgw4327hyqqr.jpg" class="activityimg" style="width:100%">
    <div class="text">(Petit) Homme-canon</div>
  </div>

  
  <div class="mySlides fade">
    <div class="numbertext">6 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453165/eznh8hj1s3a1bqxm9ndf.jpg" class="activityimg" style="width:100%">
    <div class="text">Lancé de nain!</div>
  </div>

  
  <div class="mySlides fade">
    <div class="numbertext">7 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453189/tq6izlepm9ajr23rgqhp.jpg" class="activityimg" style="width:100%">
    <div class="text">Combat de nains!</div>
  </div>
  
  <div class="mySlides fade">
    <div class="numbertext">8 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453213/mgrrbjkfzgpn0sn0fdzg.jpg" class="activityimg" style="width:100%">
    <div class="text">Lancé de nain!</div>
  </div>
  
  <div class="mySlides fade">
    <div class="numbertext">9 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453244/g4d5pq8avgtd0xybgw23.jpg" class="activityimg" style="width:100%">
    <div class="text">Des nains et plus encore!</div>
  </div>
  
  <div class="mySlides fade">
    <div class="numbertext">10 / 10</div>
    <img src="http://res.cloudinary.com/dqyvlxybo/image/upload/v1629453279/qswvtdv7arphrkw59lh2.jpg" class="activityimg" style="width:100%">
    <div class="text">La joie du nain!</div>
  </div>


</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span>
  <span class="dot" onclick="currentSlide(2)"></span>
  <span class="dot" onclick="currentSlide(3)"></span>
  <span class="dot" onclick="currentSlide(4)"></span>
  <span class="dot" onclick="currentSlide(5)"></span>
  <span class="dot" onclick="currentSlide(6)"></span>
  <span class="dot" onclick="currentSlide(7)"></span>
  <span class="dot" onclick="currentSlide(8)"></span>
  <span class="dot" onclick="currentSlide(9)"></span>
  <span class="dot" onclick="currentSlide(10)"></span>
</div>
</section>
<script>
var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";  
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}    
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 6000);
}
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%# <%= image_tag "logo.png" %>
    <%= image_tag "http://res.cloudinary.com/dqyvlxybo/image/upload/v1629215305/bgpccit8dqe6psvud6sr.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
         <%# link_to "Home", root_path, class: "nav-link" %>
        </li>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, :width=>100, :height=>100, :gravity=>"faces", :crop=>"thumb", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
            <%= image_tag "https://image.flaticon.com/icons/png/512/149/149071.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if current_user && current_user.is_dwarf == true %>
          <% if current_user && Dwarf.find_by_user_id(current_user.id) == nil %>
          <%= link_to "Create my dwarf profile", new_dwarf_path, class: "dropdown-item" %>
          <% else  %>
          <%= link_to "Edit my dwarf profile", edit_dwarf_path(Dwarf.find_by_user_id(current_user.id)), class: "dropdown-item" %>
          <% end  %>
          <hr>
        <% end %>
          <%= link_to "Edit my user profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "See the dwarves", dwarves_path, class: "dropdown-item" %>
          <%= link_to "See my rents", rents_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<form action="dwarves" method="get">
  <div class="product-search">
      <div class="search-element">
            <label class="search-label">Activité ?</label>
            <datalist id="suggestions">
                <option>Bowling</option>
                <option>Cascadeur</option>
                <option>Catcheur</option>
                <option>Combat de nain</option>
                <option>Esnabot</option>
                <option>Lancé de nain</option>
                <option>Lap dance</option>
                <option>Mètre étalon</option>
                <option>Mobilier</option>
                <option>Nain aquatique</option>
                <option>Petit Projectile</option>
                <option>Porte-clés</option>
                <option>Porte gobelet</option>
            </datalist>
          <input class="search-input" list="suggestions" placeholder="Dérouler" autocomplete="on" name="search[skill]">
      </div>
      <div class="search-element">
          <label class="search-label">Ville ?</label>
          <input class="search-input" type="text" placeholder="Ex:Paris" class="" autocomplete="on" name="search[location]">
      </div>
      <input type="submit" name="commit" class="search-button"></a>
  </div>
</form>